# Generated by Django 5.1.2 on 2024-11-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComents',
            new_name='UserComments',
        ),
    ]
