# Generated by Django 5.0.4 on 2024-05-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_person_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
