# Generated by Django 5.0.4 on 2024-07-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item_name',
            new_name='name',
        ),
    ]
