# Generated by Django 5.0.4 on 2024-07-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_remove_reservation_time_alter_menu_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='notes',
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
